"""Stat-name mappings and source-status codes (pure data, no imports)."""
from __future__ import annotations


_STAT_NAME_TO_COL = {
    "Ball possession": "possession",
    "Expected goals": "xg",
    "Expected goals on target": "xg_on_target",
    "Total shots": "shots_total",
    "Shots on target": "shots_on_target",
    "Shots off target": "shots_off_target",
    "Shots inside box": "shots_inside_box",
    "Shots outside box": "shots_outside_box",
    "Blocked shots": "blocked_shots",
    "Big chances": "big_chances",
    "Big chances missed": "big_chances_missed",
    "Corner kicks": "corners",
    "Fouls": "fouls",
    "Yellow cards": "yellow_cards",
    "Red cards": "red_cards",
    "Passes": "passes",
    "Accurate passes": "accurate_passes",
    "Offsides": "offsides",
    "Total saves": "saves",
    "Interceptions": "interceptions",
    "Recoveries": "recoveries",
    "Total tackles": "tackles",
    "Dribbles": "dribbles_won",
    "Duels": "duels_won",
    "Aerial duels": "aerial_duels_won",
    "Final third entries": "final_third",
    "Throw-ins": "throw_ins",
    "Goal kicks": "goal_kicks",
}
# Colunas do banco ↔ campos do JSON de statistics do Sofascore
_STAT_COLS = {
    "possession": "possession",
    "xg": "xg",
    "xg_on_target": "xg_on_target",
    "shots_total": "shots_total",
    "shots_on_target": "shots_on_target",
    "shots_off_target": "shots_off_target",
    "shots_inside_box": "shots_inside_box",
    "shots_outside_box": "shots_outside_box",
    "blocked_shots": "blocked_shots",
    "big_chances": "big_chances",
    "big_chances_missed": "big_chances_missed",
    "corners": "corners",
    "fouls": "fouls",
    "yellow_cards": "yellow_cards",
    "red_cards": "red_cards",
    "passes": "passes",
    "accurate_passes": "accurate_passes",
    "offsides": "offsides",
    "saves": "saves",
    "interceptions": "interceptions",
    "recoveries": "recoveries",
    "tackles": "tackles",
    "dribbles_won": "dribbles",
    "duels_won": "duels",
    "aerial_duels_won": "aerial_duels",
    "final_third_entries": "final_third",
    "throw_ins": "throw_ins",
    "goal_kicks": "goal_kicks",
}
_SOURCE_STATUS = {100: "played", 0: "scheduled"}
